### ISSUE TITLE
kafka.utils.ShutdownableThread  无法导入

### ISSUE THREAD

**Issue by EdwardWangYan** [hiSolitude/springboot-executor-kafka#1]
你好，我运行项目 发现这个包无法导入 kafka.utils.ShutdownableThread

**Comment by hiSolitude** [comment]
是不是引入的 jar 包版本问题？我使用的是 
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.11</artifactId>
            <version>0.9.0.0</version>
        </dependency>

**Comment by EdwardWangYan** [comment]
这个问题已经解决啦 我采用的是其他的方式  谢谢啦  




------------------ 原始邮件 ------------------
发件人: "Solitude"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 下午3:07
收件人: "hiSolitude/springboot-executor-kafka"<springboot-executor-kafka@noreply.github.com>;
抄送: "王艳 a21865618"<976452322@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hiSolitude/springboot-executor-kafka] kafka.utils.ShutdownableThread  无法导入 (#1)




是不是引入的 jar 包版本问题？我使用的是
 
 org.apache.kafka
 kafka_2.11
 0.9.0.0
